name: Install Splunk on EC2 (Ansible)

on:
  workflow_dispatch:

jobs:
  install_splunk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies (Ansible + SSH)
        run: |
          sudo apt update
          sudo apt install -y ansible openssh-client

      - name: Setup SSH Private Key
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/Aaa
          chmod 400 ~/.ssh/Aaa
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Create Ansible Inventory
        run: |
          mkdir -p ansible
          echo "[ec2]" > ansible/inventory.ini
          echo "${{ secrets.EC2_PUBLIC_IP }} ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/Aaa ansible_python_interpreter=/usr/bin/python3" >> ansible/inventory.ini

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection to EC2..."
          ssh -i ~/.ssh/Aaa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "echo Connected via SSH"

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/install-splunk.yml
