name: Deploy Nginx via Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Install Nginx on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install ansible

      - name: Set up SSH key
        run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/Aaa.pem
           chmod 400 ~/.ssh/Aaa.pem
           ssh-keyscan 54.91.12.34 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Run Ansible Playbook to Install Nginx
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/install-nginx.yml
