name: Deploy Nginx with Ansible

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  configure:
    name: Install Nginx on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Terraform state
        uses: actions/download-artifact@v3
        with:
          name: ec2-ip

      - name: Install Terraform (to extract IP)
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Extract public IP from Terraform state
        id: extract_ip
        run: |
          PUBLIC_IP=$(terraform output -state=terraform.tfstate -raw instance_public_ip)
          echo "EC2_PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install ansible

      - name: Set up SSH and Inventory
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/Aaa.pem
          chmod 400 ~/.ssh/Aaa.pem

          echo "[web]" > ansible/inventory.ini
          echo "$EC2_PUBLIC_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/Aaa.pem ansible_python_interpreter=/usr/bin/python3" >> ansible/inventory.ini

          ssh-keyscan -H $EC2_PUBLIC_IP >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/install-nginx.yml
